### ISSUE TITLE
Plugin doesn't seem to do anything

### ISSUE THREAD

**Issue by yennor** [splitbrain/dokuwiki-plugin-searchjump#5]
I'm using Dokuwiki 2017-02-19e "Frusterick Manners"
and the plugin doesn't seem to do anything. I used the newest version directly from git.
I could verify that the javscript gets loaded, but I didn't manage to properly debug it.

Is that plugin still under development?

**Comment by yennor** [comment]
ok. I managed to fix it. for newer versions, change in
script.js
the call:
jQuery('span.search_hit');
to
Query('span.mark');

and it should work.
Would be great if you could integrate that : -)

**Comment by splitbrain** [comment]
can you send a pull request?

**Comment by yennor** [comment]
argh. ok that was not straight forward how to do that, what happened to simple .diffs? But here  you  go:

https://github.com/splitbrain/dokuwiki-plugin-searchjump/pull/6

**Comment by yennor** [comment]
any chance that pullrequest would be integrated somewhen?

**Comment by splitbrain** [comment]
thanks for the reminder. it has been merged.
